= Internationalization (I18N)
// https://github.capgemini.com/CG-Europe-ABL/devonfw/issues/36

Read the link:https://docs.oracle.com/javase/8/docs/technotes/guides/intl/index.html[official oracle documentation] 
or the link:https://www.baeldung.com/java-8-localization[Baeldung article] about internationalization as introduction.

== Library selection

* link:https://docs.oracle.com/javase/8/docs/api/java/util/ResourceBundle.html[Java SEs ResourceBundle] for localizing messages. 
* link:https://docs.oracle.com/javase/7/docs/api/java/text/MessageFormat.html[Java SEs MessageFormat] for formatting the messages (for example variable replacement) 
* For more complex translations, use the link:https://unicode-org.github.io/icu-docs/apidoc/released/icu4j/com/ibm/icu/text/MessageFormat.html[ICU MessageFormat] library.

=== Formatting

Not only text needs internationalization.
Also consider:

* Numbers
* Dates
* Currency

Check link:https://docs.oracle.com/javase/7/docs/api/java/text/MessageFormat.html[Java SEs MessageFormat] for further links on specialized formatters.

To test ICU patterns, use this link:http://format-message.github.io/icu-message-format-for-translators/index.html[Demo page].


== Localization Properties
=== Use only property files
- Do not store key value pairs of messages and the corresponding localized message in code.
- Always create a default property and localized properties in the same folder to make it easy to keep them in sync.
- The language files should store a speaking key and a pattern containing the text to translate.
- Always use the country code in combination with the language code. This is no big overhead at the beginning and future proof.
- All language files are stored in the following structure.
----
src/main/
├─ resources/
│  ├─ i18n/
│  │  ├─ [{moduleName}]/
│  │  │  ├─ message.properties
│  │  │  ├─ message_de_DE.properties
│  │  │  ├─ message_en_US.properties
│  │  │  ├─ message_[{languageCode}]_{countryCode}].properties
----

== Translation pattern

To make it easy to translate messages inside the application, it's recommended to use an enum pattern. 

- The keys are referenced in an enum so that they can be easily used in code.
- The messages can be split according to the needs into different modules. For each module, an own enum is created.
- The enums have a translation method leading to an easy translation into the selected locale. 

View the code snipped `BookingMessages` for an example.

For the translation, the enums call a translator that encapsulates the library. This wrapper makes it easy to change the library in later. For example, when starting without ICU and pluralization is required later, it's easy to switch out the native Message Formatter with the ICU Message Formatter.

View the code snipped `MessageTranslator` for an example.


[tabs]
====
BookingMessages::
+
--
[source, java]
----
public enum BookingMessages {
  WELCOME("welcome"), // <1>
  BOOKING_DATE_SHORT("bookingDateShort");
  private final String value;
  private static final String MESSAGE_BUNDLE_NAME = "booking"; // <2>
  private static final MessageTranslator MESSAGE_TRANSLATOR = MessageTranslator.getInstance(MESSAGE_BUNDLE_NAME); // <3>
  public BookingMessage(value) { ... }
  public String translateTo(Locale locale, Object... args) {  // <4>
    return MESSAGE_TRANSLATOR.translateIn(this.value, locale, args);
  }
  public String translateTo(Object... args) { 
    // Define Locale on your needs (e.g. from user context or System.Defaul_Locale) and call <4> 
  }
}
----
<1> One enum per message. The value is the message key in the properties file
<2> The name of the location of the corresponding message bundle (/i18n/<MESSAGE_BUNDLE_NAME>/messages/)
<3> The translator for messages.
<4> A translation method using the translator
--
MessageTranslator::
+
--
The `MessageTranslator` class uses a singleton pattern. 
There should be one `MessageTranslator` instance per group of messages (in this example booking).
The group of messages is defined by the folder in which the message_<COUNTRY>.properties files are located.
Each `MessageTranslator` has an link:https://docs.oracle.com/javase/7/docs/api/java/util/ResourceBundle.html[`ResourceBundle`] per Locale. 
When a messageKey should be translated into a locale message, the translator looks up the link:https://docs.oracle.com/javase/7/docs/api/java/util/ResourceBundle.html[`ResourceBundle`] for the locale and returns the message from it.
Then link:https://unicode-org.github.io/icu/userguide/icu4j/[ICU4J] is used to format the message and replace variables.
[source, java]
----
public class MessageTranslator {
  private final static ConcurrentHashMap<String, MessageTranslator> instances = 
    new ConcurrentHashMap <>(); // <1>
  private final ConcurrentHashMap<Locale, ResourceBundle> bundleMap = new ConcurrentHashMap<>(); // <2>
  private final String BASE_DIRECTORY_NAME = "i18n";
  private final String MESSAGE_PROPERTY_PREFIX = "message";
  private final String messageBundleName; // <3>
  public static MessageTranslator getInstance(String messageBundleName) { // <1>
    return instances.computeIfAbsent(messageBundleName, MessageTranslator::new);
  }
  private MessageTranslator(String messageBundleName) { ... }
  private String getLocaleMessage(String messageKey, Locale locale) { // <4>
    String bundlePath = String.join("/", BASE_DIRECTORY_NAME, messageBundleName, MESSAGE_PROPERTY_PREFIX);
    ResourceBundle bundle = bundleMap.computeIfAbsent(locale, (key) ->
      ResourceBundle.getBundle( bundlePath, key, Thread.currentThread().getContextClassLoader()));
    return bundle.getString(patternKey);
  }
  public String translateIn(String messageKey, Locale locale, Object... arguments){
    String localeMessage = getLocaleMessage(messageKey, locale);
    MessageFormat messageFormat = new MessageFormat(localeMessage, locale);
    return messageFormat.format(arguments, new StringBuffer(), new FieldPosition(0)).toString(); // <5>
  }
  // Add overloaded methods of translateIn depending on your needs. 
  // For example using a specific locale by default (e.g. system default or from user context)
}
----
<1> A `MessageTranslator` instance exists for each group of messages. 
<2> A `MessageTranslator` instance has a link:https://docs.oracle.com/javase/7/docs/api/java/util/ResourceBundle.html[`ResourceBundle`] per locale.
<3> The messageBundles are stored in the same folder with the pattern `i18n/<messageBundleName>/message_<LOCALE>.properties`
<4> Returns the message from the locale-specific link:https://docs.oracle.com/javase/7/docs/api/java/util/ResourceBundle.html[`ResourceBundle`] using the bundleMap.
<5> Uses the ICU's link:https://unicode-org.github.io/icu-docs/apidoc/dev/icu4j/com/ibm/icu/text/MessageFormat.html[`MessageFormat`] to format the message based on the arguments and the locale.
--
message_en_US.properties::
+
--
----
welcome=Welcome {0}
bookingDateShort=Your table is booked at {0, date, short}. <1>
----
<1> Will return the date in a numeric format depending on LOCALE (e.g. 24.10.22 in german or 10/24/22 in US). See link:https://unicode-org.github.io/icu/userguide/format_parse/datetime/[ICU Formatting details].
--
====


=== Usage example
[source,java]
----
String welcomeText = BookingMessages.WELCOME.translate("Peter");
System.out.println(welcomeText);
----

In this example, the constant `WELCOME` from the enum `BookingMessages` is used to call the "translate" function. The "translate" function is then using the `MessageTranslator` to convert the message into the current locale language. To make this possible, the translator is using a ResourceBundler to obtain the message text from the `message.properties` file and the Messageformatter to replace the placeholder with the input "Peter". After the translation, the message is returned.


image::TranslationFlow.drawio.svg["Translation Flow"]


== Retrieve locale

=== Use accept-language in http calls

The link:https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language[accept-language] header indicates the natural language and locale of the client.
This should always result in a link:https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Language[Content-Language] header in the response.

=== Logged in user

If a user is authenticated, this user might have some localization preferences.
Those settings might be stored in the application itself (e.g. the database) or in the authentication system (e.g. LDAP).

=== Business context

The localization specifics might also result from business specific indicators (e.g. A flag in a message or defined values). 
Discuss with business responsibles on this topic.


=== Further references

* https://docs.oracle.com/javase/8/docs/api/java/util/ResourceBundle.html
* https://www.baeldung.com/java-localization-messages-formatting