= JSON

JSON (JavaScript Object Notation) is a format to represent and exchange data in a human readable form.
See https://www.json.org/json-en.html for a formal definition. 
JSON is easier explained here: https://www.w3schools.com/js/js_json_intro.asp.

== JSON parser

devonfw recommends link:https://github.com/FasterXML/jackson[FasterXMLs Jackson] as JSON parser. There's a useful series on Jackson on Baeldung:
https://www.baeldung.com/jackson


[tabs] 
==== 
Spring:: 
+ 
-- 
Spring offers a default support for mapping with Jackson, when spring-starter-web is used.
--

Quarkus::
+
--
Quarkus offers the following extension:

This extension adds the usual quarkus-resteasy-reactive functionality and adds the mapping using Jackson.

https://quarkus.io/guides/rest-json
--
====

=== Use ISO8601 in UTC for timestamp representation

It's recommended to use link:https://en.wikipedia.org/wiki/ISO_8601[ISO 8601] as timestamp representation `yyyy-MM-dd'T'HH:mm:ssXXX`.
Furthermore, always send timezones in UTC.

This can be achieved on a `ZonedDateTime` field with the following annotation:

[soure,java]
----
@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ssXXX", timezone = "UTC", lenient = OptBoolean.TRUE)
----

=== Send monetary amounts as separation of amount and currency

Monetary amounts should be best representated as object consisting of the actual amount and the currency.
[soure,javascript]
----
...
"money": {
  "amount": 200.00,
  "currency": "USD"
  },
...
----

link:https://github.com/zalando/jackson-datatype-money[Zalandos Jackson Datatype Money] is a implementation for this.

== Example

- https://github.com/devonfw/java-samples/tree/main/integration/rest-json

== References
- https://stackoverflow.com/questions/30362446/deserialize-json-with-jackson-into-polymorphic-types-a-complete-example-is-giv
- https://www.baeldung.com/jackson
